apiVersion: v1
kind: ConfigMap
metadata:
  name: node-rest-api-settings
  namespace: iamnsharma-k8s
data:
  MONGODB_URI: mongodb+srv://admin:admin@mymongodb.k4ouxrx.mongodb.net/nestjs-demo?retryWrites=true&w=majority
  DB_NAME: nagp
  DB_USER: admin
  USER_NAME: K8-dev_testuser
