apiVersion: v1
kind: ConfigMap
metadata:
  name: node-rest-api-settings
  namespace: iamnsharma-k8s
data:
  MONGODB_URI: mongodb://adminuser:password123@mongodb-service-ip:27017
  DB_NAME: nagp
  DB_USER: adminuser
  USER_NAME: K8-dev_testuser
