apiVersion: v1
kind: ConfigMap
metadata:
  name: node-rest-api-settings
  namespace: iamnsharma-k8s
data:
  MONGODB_HOST: mongodb-service-ip
  MONGODB_PORT: "27017"
  MONGODB_DB: nagp
  MONGODB_AUTH_SOURCE: admin
  USER_NAME: K8-dev_testuser
