apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-rest-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-rest-api
  template:
    metadata:
      labels:
        app: node-rest-api
    spec:
      containers:
      - name: node-rest-api
        image: iamnsharma/node-rest-api:v7
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        envFrom:  
          - configMapRef:
              name: node-rest-api-settings
          - secretRef:
              name: node-rest-api-secret-info

---
apiVersion: v1
kind: Service
metadata:
  name: node-rest-lb
spec:
  type: LoadBalancer
  selector:
    app: node-rest-api
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP

# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   namespace: iamnsharma-k8s
#   name: node-rest-api-deployment-autoscale
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: node-rest-api-deployment
#   targetCPUUtilizationPercentage: 10
#   minReplicas: 1
#   maxReplicas: 4
  # metrics:
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       type: Utilization
  #       averageUtilization: 10

