apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-rest-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-rest-api
  template:
    metadata:
      labels:
        app: node-rest-api
    spec:
      containers:
        - name: node-rest-api
          image: iamnsharma/node-rest-api:v8
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: node-rest-api-settings
            - secretRef:
                name: node-rest-api-secret-info
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: node-rest-lb
spec:
  type: LoadBalancer
  selector:
    app: node-rest-api
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
