apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: iamnsharma-k8s
spec:
  storageClassName: mongodb-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi



