# Secret Deployment
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: iamnsharma-k8s
type: Opaque
data:
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQxMjM=
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
---
# Storage Class Deployment
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-storage-class
  namespace: iamnsharma-k8s
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
---
# Persistent Volume Claim Deployment
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: iamnsharma-k8s
spec:
  storageClassName: mongodb-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: iamnsharma-k8s
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: mongo
          name: mongodb
          args: ["--dbpath", "/data/db"]
          envFrom:
            - secretRef:
                name: mongodb-secrets
          volumeMounts:
            - name: "mongo-data-dir"
              mountPath: "/data/db"
      volumes:
        - name: "mongo-data-dir"
          persistentVolumeClaim:
            claimName: "mongodb-data"
---
# Service Deployment
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-ip
  namespace: iamnsharma-k8s
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
