# This file contains the deployment and service configuration for the node-rest-api application.

# Secrets Deployment
apiVersion: v1
kind: Secret
metadata:
  name: node-rest-api-secret-info
  namespace: iamnsharma-k8s
type: Opaque
data:
    MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQxMjM=
    MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
---
# ConfigMap Deployment
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-rest-api-settings
  namespace: iamnsharma-k8s
data:
  MONGODB_HOST: mongodb-service-ip
  MONGODB_PORT: "27017"
  MONGODB_DB: nagp
  MONGODB_AUTH_SOURCE: admin
  PORT: "3000"
  USER_NAME: K8-dev_testuser
---
# Node REST API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-rest-api-deployment
  namespace: iamnsharma-k8s
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-rest-api
  template:
    metadata:
      labels:
        app: node-rest-api
    spec:
      containers:
        - name: node-rest-api
          image: iamnsharma/node-rest-api:v10
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: node-rest-api-settings
            - secretRef:
                name: node-rest-api-secret-info
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"

---
# Node REST API Service Deployment
apiVersion: v1
kind: Service
metadata:
  name: node-rest-lb
  namespace: iamnsharma-k8s
spec:
  type: LoadBalancer
  selector:
    app: node-rest-api
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
