apiVersion: v1
kind: Service
metadata:
  namespace: iamnsharma-k8s
  name: mongo-nodeport-svc
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 300080
