apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: iamnsharma-k8s
  name: node-rest-api-deployment-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-rest-api-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
