apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-client
  namespace: iamnsharma-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-client
  strategy: {}
  template:
    metadata:
      labels:
        app: mongo-client
    spec:
      containers:
      - image: mongo
        name: mongo-client
        env:
        - name: mongo-client_INITDB_ROOT_USERNAME
          value: 'admin'
        - name: mongo-client_INITDB_ROOT_PASSWORD
          value: 'admin'